"""
OmniAgentPay SDK Onboarding Utilities.

Handles one-time Circle Developer-Controlled Wallets setup:
- Generate Entity Secret
- Register Entity Secret with Circle
- Save recovery file
- Create .env file with credentials

This makes onboarding as easy as:
    >>> from omniagentpay.onboarding import quick_setup
    >>> quick_setup("YOUR_CIRCLE_API_KEY")
"""

from __future__ import annotations

import os
import secrets
from pathlib import Path
from typing import Any

# Circle SDK utilities for entity secret management
try:
    from circle.web3 import utils as circle_utils
    CIRCLE_SDK_AVAILABLE = True
except ImportError:
    CIRCLE_SDK_AVAILABLE = False
    circle_utils = None


class SetupError(Exception):
    """Error during SDK setup."""
    pass


def generate_entity_secret() -> str:
    """Generate a new 32-byte Entity Secret."""
    # Generate 32 random bytes and encode as hex
    return secrets.token_hex(32)


def register_entity_secret(
    api_key: str,
    entity_secret: str,
    recovery_file_path: str | Path | None = None,
) -> dict[str, Any]:
    """Register an Entity Secret with Circle."""
    if not CIRCLE_SDK_AVAILABLE:
        raise SetupError(
            "Circle SDK not installed. Run: pip install circle-developer-controlled-wallets"
        )
    
    # Validate entity secret format
    if len(entity_secret) != 64:
        raise SetupError(f"Entity Secret must be 64 hex characters, got {len(entity_secret)}")
    
    try:
        int(entity_secret, 16)
    except ValueError:
        raise SetupError("Entity Secret must be valid hexadecimal")
    
    # Default recovery file directory (Circle SDK expects a directory path)
    if recovery_file_path is None:
        recovery_file_path = "./"
    
    recovery_dir = Path(recovery_file_path).resolve()
    
    # If a file path was given, use the parent directory
    if recovery_dir.suffix:  # Has file extension, it's a file path
        recovery_dir = recovery_dir.parent
    
    # Ensure directory exists
    recovery_dir.mkdir(parents=True, exist_ok=True)
    
    try:
        result = circle_utils.register_entity_secret_ciphertext(
            api_key=api_key,
            entity_secret=entity_secret,
            recoveryFileDownloadPath=str(recovery_dir),
        )
        return result
    except Exception as e:
        raise SetupError(f"Failed to register entity secret: {e}") from e


def create_env_file(
    api_key: str,
    entity_secret: str,
    env_path: str | Path = ".env",
    network: str = "ARC-TESTNET",
    overwrite: bool = False,
) -> Path:
    """Create a .env file with Circle credentials."""
    env_path = Path(env_path)
    
    if env_path.exists() and not overwrite:
        raise SetupError(
            f"{env_path} already exists. Use overwrite=True to replace."
        )
    
    env_content = f"""# OmniAgentPay SDK Configuration
# Generated by omniagentpay.onboarding

# Circle API Credentials
CIRCLE_API_KEY={api_key}
ENTITY_SECRET={entity_secret}

# Network Configuration
OMNIAGENTPAY_NETWORK={network}

# Optional: Default wallet ID (set after creating a wallet)
# OMNIAGENTPAY_DEFAULT_WALLET=
"""
    
    env_path.write_text(env_content)
    return env_path


def quick_setup(
    api_key: str,
    env_path: str | Path = ".env",
    recovery_path: str | Path = "./circle_recovery.dat",
    network: str = "ARC-TESTNET",
) -> dict[str, Any]:
    """
    Complete SDK setup in one call.
    
    This function:
    1. Generates a new Entity Secret
    2. Registers it with Circle
    3. Saves the recovery file
    4. Creates a .env file with credentials
    """
    print("OmniAgentPay Quick Setup")
    print("=" * 40)
    
    # Step 1: Generate Entity Secret
    print("\nGenerating Entity Secret...")
    entity_secret = generate_entity_secret()
    print(f"Generated 32-byte secret")
    
    # Step 2: Register with Circle
    print("\nRegistering with Circle...")
    try:
        registration = register_entity_secret(
            api_key=api_key,
            entity_secret=entity_secret,
            recovery_file_path=recovery_path,
        )
        print(f"Registered successfully")
        print(f"Recovery file saved in directory: {recovery_path}")
    except SetupError as e:
        print(f"Registration failed: {e}")
        raise
    
    # Step 3: Create .env file
    print("\nCreating .env file...")
    env_file = create_env_file(
        api_key=api_key,
        entity_secret=entity_secret,
        env_path=env_path,
        network=network,
        overwrite=True,
    )
    print(f"Created: {env_file}")
    
    print("\n" + "=" * 40)
    print("Setup Complete!")
    print("\nIMPORTANT: Save these securely:")
    print(f"   - Entity Secret: {entity_secret[:8]}...{entity_secret[-8:]}")
    print(f"   - Recovery File: {recovery_path}")
    print("\nNext steps:")
    print("   1. Keep recovery file safe (you'll need it if secret is lost)")
    print("   2. Add .env to .gitignore")
    print("   3. Start using the SDK!")
    print("\n   >>> from omniagentpay import Config")
    print("   >>> config = Config.from_env()")
    
    return {
        "entity_secret": entity_secret,
        "env_path": str(env_file),
        "recovery_path": str(recovery_path),
        "registration": registration,
    }


def auto_setup_entity_secret(
    api_key: str,
    env_path: str | Path = ".env",
    recovery_path: str | Path = "./",
    logger: "logging.Logger | None" = None,
) -> str:
    """Silently auto-generate and register entity secret."""
    import logging
    log = logger or logging.getLogger("omniagentpay.onboarding")
    
    # Generate
    entity_secret = generate_entity_secret()
    
    # Register
    try:
        registration = register_entity_secret(
            api_key=api_key,
            entity_secret=entity_secret,
            recovery_file_path=recovery_path,
        )
    except SetupError:
        # Log warning but continue - secret was generated
        log.warning(
            "Entity secret generated but registration failed. "
            "You may need to run setup manually."
        )
        raise
    
    # Update or create .env
    env_file = Path(env_path)
    if env_file.exists():
        # Append to existing
        with open(env_file, "a") as f:
            f.write(f"\n# Auto-generated entity secret\n")
            f.write(f"ENTITY_SECRET={entity_secret}\n")
    else:
        # Create new
        create_env_file(
            api_key=api_key,
            entity_secret=entity_secret,
            env_path=env_path,
        )
    
    # Also set in current environment
    os.environ["ENTITY_SECRET"] = entity_secret
    
    # Log file locations
    recovery_dir = Path(recovery_path).resolve()
    log.info(
        f"Entity secret auto-generated and registered.\n"
        f"  .env file: {env_file.resolve()}\n"
        f"  Recovery file saved in: {recovery_dir}\n"
        f"  Keep these files safe!"
    )
    
    return entity_secret


def verify_setup() -> dict[str, bool]:
    """Verify that SDK is properly configured."""
    results = {
        "circle_sdk_installed": CIRCLE_SDK_AVAILABLE,
        "api_key_set": bool(os.getenv("CIRCLE_API_KEY")),
        "entity_secret_set": bool(os.getenv("ENTITY_SECRET")),
        "ready": False,
    }
    
    results["ready"] = all([
        results["circle_sdk_installed"],
        results["api_key_set"],
        results["entity_secret_set"],
    ])
    
    return results


def print_setup_status() -> None:
    """Print human-readable setup status."""
    status = verify_setup()
    
    print("OmniAgentPay SDK Status")
    print("=" * 30)
    
    def check(ok: bool) -> str:
        return "✓" if ok else "✗"
    
    print(f"  {check(status['circle_sdk_installed'])} Circle SDK installed")
    print(f"  {check(status['api_key_set'])} CIRCLE_API_KEY set")
    print(f"  {check(status['entity_secret_set'])} ENTITY_SECRET set")
    print()
    
    if status["ready"]:
        print("Ready to use!")
    else:
        print("Setup incomplete. Run:")
        print("   >>> from omniagentpay.onboarding import quick_setup")
        print("   >>> quick_setup('YOUR_API_KEY')")


def load_env_file(env_path: str | Path = ".env") -> dict[str, str]:
    """Load environment variables from .env file."""
    env_path = Path(env_path)
    env_vars = {}
    
    if not env_path.exists():
        return env_vars
    
    for line in env_path.read_text().splitlines():
        line = line.strip()
        # Skip comments and empty lines
        if not line or line.startswith("#"):
            continue
        
        if "=" in line:
            key, _, value = line.partition("=")
            env_vars[key.strip()] = value.strip()
    
    return env_vars


def update_env_file(
    env_path: str | Path,
    updates: dict[str, str],
) -> Path:
    """Update existing .env file with new values."""
    env_path = Path(env_path)
    
    # Load existing content
    if env_path.exists():
        existing = load_env_file(env_path)
        content_lines = env_path.read_text().splitlines()
    else:
        existing = {}
        content_lines = ["# OmniAgentPay SDK Configuration", ""]
    
    # Update existing lines and track what we've updated
    updated_keys = set()
    new_lines = []
    
    for line in content_lines:
        if "=" in line and not line.strip().startswith("#"):
            key = line.partition("=")[0].strip()
            if key in updates:
                new_lines.append(f"{key}={updates[key]}")
                updated_keys.add(key)
            else:
                new_lines.append(line)
        else:
            new_lines.append(line)
    
    # Add any new keys that weren't in the file
    for key, value in updates.items():
        if key not in updated_keys:
            new_lines.append(f"{key}={value}")
    
    env_path.write_text("\n".join(new_lines) + "\n")
    return env_path


def ensure_setup(
    api_key: str | None = None,
    env_path: str | Path = ".env",
    recovery_path: str | Path = "./circle_recovery.dat",
    network: str = "ARC-TESTNET",
) -> dict[str, Any]:
    """Ensure SDK is fully set up, automatically registering entity secret if needed."""
    env_path = Path(env_path)
    print("OmniAgentPay Setup Check")
    print("=" * 40)
    
    # Step 1: Load existing .env if present
    print("\nChecking .env file...")
    env_vars = load_env_file(env_path)
    
    if env_vars:
        print(f"   ✓ Found .env with {len(env_vars)} variables")
        # Set env vars from file
        for key, value in env_vars.items():
            os.environ.setdefault(key, value)
    else:
        print(f"   → No .env found at {env_path}")
    
    # Step 2: Determine API key
    print("\nChecking CIRCLE_API_KEY...")
    final_api_key = api_key or os.getenv("CIRCLE_API_KEY")
    
    if not final_api_key:
        raise SetupError(
            "CIRCLE_API_KEY not found. Either:\n"
            "  1. Pass api_key parameter: ensure_setup(api_key='YOUR_KEY')\n"
            "  2. Set CIRCLE_API_KEY in .env file\n"
            "  3. Set CIRCLE_API_KEY environment variable"
        )
    
    print(f"   ✓ API Key: {final_api_key[:8]}...{final_api_key[-4:]}")
    os.environ["CIRCLE_API_KEY"] = final_api_key
    
    # Step 3: Check entity secret
    print("\nChecking ENTITY_SECRET...")
    entity_secret = os.getenv("ENTITY_SECRET")
    registration_result = None
    
    if entity_secret:
        print(f"   ✓ Entity Secret found: {entity_secret[:8]}...{entity_secret[-4:]}")
    else:
        print("   → Entity Secret not found, generating...")
        
        # Generate new entity secret
        entity_secret = generate_entity_secret()
        print(f"   ✓ Generated: {entity_secret[:8]}...{entity_secret[-4:]}")
        
        # Register with Circle
        print("\nRegistering Entity Secret with Circle...")
        try:
            registration_result = register_entity_secret(
                api_key=final_api_key,
                entity_secret=entity_secret,
                recovery_file_path=recovery_path,
            )
            print(f"   ✓ Registered successfully")
            print(f"   ✓ Recovery file saved: {recovery_path}")
        except SetupError as e:
            print(f"Registration failed: {e}")
            raise
        
        # Update .env file
        print("\nUpdating .env file...")
        update_env_file(env_path, {
            "CIRCLE_API_KEY": final_api_key,
            "ENTITY_SECRET": entity_secret,
            "OMNIAGENTPAY_NETWORK": network,
        })
        print(f"   ✓ Updated: {env_path}")
        
        # Set environment variable
        os.environ["ENTITY_SECRET"] = entity_secret
    
    # Set network
    os.environ.setdefault("OMNIAGENTPAY_NETWORK", network)
    
    print("\n" + "=" * 40)
    print("SDK Ready to Use!")
    print("\n>>> from omniagentpay import Config")
    print(">>> config = Config.from_env()")
    
    return {
        "ready": True,
        "api_key": final_api_key,
        "entity_secret": entity_secret,
        "entity_secret_registered": registration_result is not None,
        "registration": registration_result,
        "env_path": str(env_path),
    }

